import { Roboto } from "next/font/google"; //font family
import "./globals.css";
import Header from "../components/layout/Header";

const roboto = Roboto({ subsets: ["latin"], weight: ["400", "500", "700"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="">
      <body className={roboto.className}>
        <main className="mx-auto">
          <Header />
          {children}
          <footer className="text-center border-t p-4 text-gray-500 mt-16">
            &copy; 2024 All Rights Reserved
          </footer>
        </main>
      </body>
    </html>
  );
}
